### ISSUE TITLE
createDir fails

### ISSUE THREAD

**Issue by cloelke** [thephpleague/flysystem-azure-blob-storage#2]
I added the following to the createDir function

 $this->write(rtrim($dirname, '/') . '/', 'dir', $config);

I had it with out the dir content the same as the flysystem-azure-blob version, but that also fails

**Comment by ColinLaws** [comment]
The Azure REST client does not appear to implement behavior for explicitly creating directories. Instead of creating the directory, and then writing the file, just write the file using the path structure you want, and Azure will implement that structure. 

If you take a look at where createDir is implemented, it's just returning an array, that's why it's not creating anything. 

```php
public function createDir($dirname, Config $config)
{
    return ['path' => $dirname, 'type' => 'dir'];
}
```

**Comment by frankdejonge** [comment]
I think this changes after the issue was created, so should be solved now. @ColinLaws' comment is correct.
