### ISSUE TITLE
Unable to use use client object in other classes

### ISSUE THREAD

**Issue by bsomeshwer** [thephpleague/flysystem-azure-blob-storage#20]
Hi,

Could you please add getter method to the following class called "League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter.php" as follows:

   ```
 /** Getter method for a private property client */
    public function getClient()
    {
        return $this->client;
    }
```
So that I can use client object by using that method in other classes as private properties can not be accessed outside. 

**Issue Background:**
In my project we wanted to fetch the metadata of a file in the blob storage and base on that metadata we are performing some operations.  Here, we just wanted to call the method "getBlobMetaData()" which returns metadata of a blob. But this must be called by using Client object where as we are unable to get client object since there is no getter method available to get this private property of a class called "client".

Thanks

**Comment by frankdejonge** [comment]
Hi @bsomeshwer,

You can call this method directly on the client, Flysystem does not need to be in the middle of this. Other adapters have this functionality and I regret putting it in. It promotes Flysystem to a service locator, which is it is not. If you absolutely must have this functionality, you can extend the adapter, overwrite the constructor and store it in a property to expose in a getter.

**Comment by atrauzzi** [comment]
@frankdejonge - When using flysystem in Laravel, it's already wrapped in a system that provides configuration. To force people to do it the way you suggest means they have to configure it twice.

There's not anything necessarily wrong with getting the client instance through flysystem as flysystem is itself already being "located".

**Comment by frankdejonge** [comment]
@atrauzzi I'm not forcing anybody to do anything. You may not think there's anything wrong with using Flysystem as a service locator, but I do. By providing access to every underlying resource, the design has abstraction leak, which is bad. It would also make the interface larger, which is bad for maintenance and package stability. Adding one thing opens the door to allowing anything, because if X why not Y, right? You should ask Laravel to provide direct access to the underlying resource instead of trying to get it from Flysystem. 

If anything, this package reduces a lot of code for its users, and so does Laravel by integrating it. If it doesn't 100% fit you, take that into account when you start complaining about it. Is it too much to ask you to create an instance of an SDK? You man not agree with my decisions, but you should have the decency to respect them.

**Comment by atrauzzi** [comment]
:thinking: Yikes ,it's not a question of _respect_ man.

It's that using the phrase _"service locator"_ isn't quite airtight. If only because (and I know you obviously already know this) it overlooks that by the time someone has a flysystem instance, they've already gone through something akin to service location (Laravel disks).

By that point we're talking about a getter.  So sure, I could see your point about death-by-a-thousand-cuts.  But that won't create any burden on this library as people can just fall back on the service-location-like mechanisms they used to infer the type of the flysystem adapter.

To genuinely answer your question... I do feel it does risk some weird boilerplate redundancy to ask people to create a second instance of the SDK. No, it's not the end of the world, but what this ticket asks for is a nice solution and what you're suggesting are workarounds.

**Comment by sagikazarmark** [comment]
First of all: calling out a maintainer for "forcing" you/others to do something or implying that they consciuosly cause harm to you/others because they don't add something to a library they maintain (and give you for free) **is disrespectful**. 

Secondly, I haven't seen any evidence that supports the OP's request makes sense, other than that it would be more comfortable for some use cases. This kind of "support" is counterproductive and selfish. You are clearly asking something the author doesn't want to do and for good reason (that he explained well), but you are still pushing it without any actual arguments.

From a professional point of view, this request promotes bad practice and the author explained that in detail.

The author also offered alternative solutions (bring it to laravel to make the client available, create a new one). As far as I can see, you've given no proper counter arguments why those are "workarounds" for you. I'm sorry, but "weird boilerplate redundancy" is not an argument.

**Comment by GrahamCampbell** [comment]
Couldn't agree more with @frankdejonge.

**Comment by atrauzzi** [comment]
I understand that this has gone to the court of popular opinion and that clique logic is now in play. I'll simply defend my angle: I was advocating that someone other than me had the same idea and I disagreed with the rationale for rejecting it. Nobody was _"called out"_, and my goodness what a neurotic conclusion to jump to.

Anyway, I did enough to explain it (_There's not anything necessarily wrong with getting the client instance through flysystem as flysystem is itself already being "located"._), if the attempt to advocate for the idea one more time was well received, I'd have offered to contribute the change. It's not, life goes on.

The speed at which this escalated is a little stifling.
